FROM magicalion/singleuser:gpu-cas

USER $NB_UID

EXPOSE 8888
WORKDIR $HOME/input/work

USER root

ADD sc.py /usr/lib/python3.5/sitecustomize.py

ADD run_job_cas.sh $HOME
RUN mv $HOME/run_job_cas.sh $HOME/run_job.sh
RUN chown jovyan:users $HOME/run_job.sh

ADD job_funcs.py $HOME
RUN chown jovyan:users $HOME/job_funcs.py

ADD mnist.py $HOME
RUN chown jovyan:users $HOME/mnist.py

CMD ['bash', '/mnt/run_job.sh']
