FROM magicalion/singleuser:latest-gpu

USER $NB_UID

EXPOSE 8888
WORKDIR /home/$NB_USER/work

USER root

ADD run_job.sh /home/jovyan
RUN chown jovyan:users /home/jovyan/run_job.sh

ADD job_funcs.py /home/jovyan
RUN chown jovyan:users /home/jovyan/job_funcs.py

CMD ['bash', '/home/jovyan/run_job.sh']
